#!/usr/bin/env python3
"""Regenerate the implementation-support block in docs/compatibility.md.

The compatibility matrix on that page is a SPEC fact: what the normative text
is written against, one row per dependency, implementation-independent, and
hand-maintained. This script owns a different, clearly-separated block on the
same page: what each IMPLEMENTATION requires and has verified, published by
the implementation itself.

Everything between the markers is rewritten wholesale; nothing outside them is
touched.

Run modes:
  default               regenerate docs/compatibility.md in place
  --check               exit 1 if docs/compatibility.md would change (CI mode)
  --offline-python PATH use a local TOML file for the Python manifest
                        instead of fetching from the published URL
                        (useful for testing and air-gapped builds)

Schema (TOML, in each implementation's `conformance.toml`):
  [external_dependencies.<slug>]
  requires    = ">=4.6,<5"     # required: the range published to consumers
  verified    = "4.7.1"        # required: the single version exercised
  verified_on = "2026-08-13"   # required: ISO date that pin was last moved
  internals   = ["a.b.C", ...] # optional: private surface depended on
  note        = "..."          # optional: free text, rendered under the table
                               #   as a single paragraph (whitespace collapsed)

Degradation is deliberate and asymmetric. An implementation must never be
blocked on a spec-side change, and a spec-side build must never break because
an implementation pushed:

  - no `[external_dependencies]` section  -> empty state, not an error
  - a slug with no DEPENDENCY_NAMES entry -> renders as the raw slug
  - a missing REQUIRED key                -> hard failure (a half-rendered row
                                             asserting a number it does not
                                             have is worse than a red build)
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

import _impl_manifest

ROOT = Path(__file__).resolve().parent.parent
COMPATIBILITY_DOC = ROOT / "docs" / "compatibility.md"

BEGIN_MARKER = "<!-- BEGIN GENERATED: implementation-dependencies -->"
END_MARKER = "<!-- END GENERATED: implementation-dependencies -->"

DO_NOT_EDIT = (
    "<!-- Regenerated by scripts/regenerate_impl_dependencies.py from each "
    "implementation's published conformance manifest. Edits between the markers "
    "are overwritten. -->"
)

# Spec-side display names for the dependency slugs implementations publish.
# Names are deliberately language-neutral: one slug can be depended on by
# implementations in different languages through different packages.
# A slug with no entry here renders as itself.
DEPENDENCY_NAMES = {
    "langfuse": "Langfuse SDK",
}

REQUIRED_KEYS = ("requires", "verified", "verified_on")

EMPTY_STATE = (
    "*No implementation currently publishes an `[external_dependencies]` section in its\n"
    "conformance manifest. This block populates automatically once one does.*"
)


def _inline(text: str) -> str:
    """Normalize a manifest-sourced string for inline markdown rendering.

    Manifest values are external input landing in a table row and a list item,
    where a newline breaks the row and a pipe splits the cell. Collapse
    whitespace (a TOML multi-line string is a formatting choice, not a semantic
    one) and escape the cell delimiter.

    Caveat on the escape: Python-Markdown unescapes `\\|` in plain cell text but
    leaves the backslash visible inside a code span, so a pipe in one of the
    backticked fields renders as `\\|`. That is accepted rather than solved.
    A pipe cannot occur in a version range or a dotted symbol path, and no
    representation of a pipe inside a code span in a table exists anyway; a
    visible backslash in an impossible case beats a corrupted table.
    """
    return " ".join(text.split()).replace("|", "\\|")


def collect_rows(manifests: list[tuple[str, dict]]) -> list[dict]:
    """Flatten every implementation's dependency entries into render rows."""
    rows: list[dict] = []
    for label, manifest in manifests:
        deps = manifest.get("external_dependencies", {})
        if not isinstance(deps, dict):
            raise RuntimeError(
                f"{label}: [external_dependencies] must be a table, got "
                f"{type(deps).__name__}"
            )
        for slug in sorted(deps):
            entry = deps[slug]
            if not isinstance(entry, dict):
                raise RuntimeError(
                    f"{label}: [external_dependencies.{slug}] must be a table, got "
                    f"{type(entry).__name__}"
                )
            missing = [k for k in REQUIRED_KEYS if not entry.get(k)]
            if missing:
                raise RuntimeError(
                    f"{label}: [external_dependencies.{slug}] is missing required "
                    f"key(s): {', '.join(missing)}"
                )
            # Type-check the shape as well as its presence. A bare string
            # `internals` is the case that matters: it would not raise, it would
            # iterate into characters and render a count and a list that are
            # both wrong, which is worse on a public page than a red build.
            mistyped = [k for k in REQUIRED_KEYS if not isinstance(entry[k], str)]
            if mistyped:
                raise RuntimeError(
                    f"{label}: [external_dependencies.{slug}] key(s) "
                    f"{', '.join(mistyped)} must be strings"
                )
            internals = entry.get("internals") or []
            if not isinstance(internals, list) or not all(
                isinstance(path, str) for path in internals
            ):
                raise RuntimeError(
                    f"{label}: [external_dependencies.{slug}] internals must be an "
                    "array of strings"
                )
            note = entry.get("note", "")
            if not isinstance(note, str):
                raise RuntimeError(
                    f"{label}: [external_dependencies.{slug}] note must be a string"
                )
            rows.append(
                {
                    "implementation": _inline(label),
                    "dependency": _inline(DEPENDENCY_NAMES.get(slug, slug)),
                    "requires": _inline(entry["requires"]),
                    "verified": _inline(entry["verified"]),
                    "verified_on": _inline(entry["verified_on"]),
                    "internals": [_inline(path) for path in internals],
                    "note": _inline(note),
                }
            )
    rows.sort(key=lambda r: (r["implementation"], r["dependency"]))
    return rows


def render_block(rows: list[dict]) -> str:
    """Render the full marker-delimited block, markers included.

    Carries no generation timestamp on purpose: a date would change the block
    on every run and make `--check` unconditionally red.
    """
    lines = [BEGIN_MARKER, DO_NOT_EDIT, ""]

    if not rows:
        lines += [EMPTY_STATE, "", END_MARKER]
        return "\n".join(lines)

    lines.append("| Implementation | Dependency | Requires | Verified | Verified on | Internals |")
    lines.append("|---|---|---|---|---|---|")
    for r in rows:
        internals = str(len(r["internals"])) if r["internals"] else "None declared"
        lines.append(
            f"| {r['implementation']} | {r['dependency']} | `{r['requires']}` | "
            f"`{r['verified']}` | {r['verified_on']} | {internals} |"
        )
    lines.append("")

    noted = [r for r in rows if r["note"]]
    if noted:
        lines.append("Implementation notes:")
        lines.append("")
        for r in noted:
            lines.append(f"- **{r['implementation']} / {r['dependency']}:** {r['note']}")
        lines.append("")

    for r in rows:
        if not r["internals"]:
            continue
        count = len(r["internals"])
        plural = "" if count == 1 else "s"
        lines.append(
            f'??? note "{r["implementation"]}: {r["dependency"]} private surface '
            f'({count} path{plural})"'
        )
        lines.append("")
        for path in r["internals"]:
            lines.append(f"    - `{path}`")
        lines.append("")

    lines.append(END_MARKER)
    return "\n".join(lines)


def splice(text: str, block: str) -> str:
    """Replace the marker-delimited region of the page with a fresh block."""
    start = text.find(BEGIN_MARKER)
    end = text.find(END_MARKER)
    if start == -1 or end == -1:
        raise RuntimeError(
            f"{COMPATIBILITY_DOC.relative_to(ROOT)} is missing the generated-block "
            f"markers ({BEGIN_MARKER} / {END_MARKER})"
        )
    if end < start:
        raise RuntimeError(
            f"{COMPATIBILITY_DOC.relative_to(ROOT)} has its generated-block markers "
            "in the wrong order"
        )
    return text[:start] + block + text[end + len(END_MARKER) :]


def main() -> int:
    ap = argparse.ArgumentParser(
        description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter
    )
    ap.add_argument("--check", action="store_true", help="exit 1 if docs/compatibility.md would change")
    ap.add_argument(
        "--offline-python",
        help="path to a local Python conformance.toml (instead of fetching the URL)",
    )
    args = ap.parse_args()

    offline = {"python": args.offline_python}
    manifests = []
    for impl in _impl_manifest.MANIFEST_URLS:
        manifest = _impl_manifest.fetch_manifest(impl, offline.get(impl))
        manifests.append((_impl_manifest.implementation_label(impl, manifest), manifest))

    original = COMPATIBILITY_DOC.read_text(encoding="utf-8")
    updated = splice(original, render_block(collect_rows(manifests)))

    if args.check:
        if original != updated:
            sys.stderr.write(
                "docs/compatibility.md implementation-support block is out of date.\n"
                "Run: python scripts/regenerate_impl_dependencies.py\n"
            )
            return 1
        print("docs/compatibility.md implementation-support block is up to date.")
        return 0

    if original != updated:
        COMPATIBILITY_DOC.write_text(updated, encoding="utf-8")
        print(f"updated {COMPATIBILITY_DOC.relative_to(ROOT)}")
    else:
        print(f"no changes to {COMPATIBILITY_DOC.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
